# Generated by OmopViewer 0.6.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    cohort_code_use = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE,
    incidence = FALSE,
    incidence_attrition = FALSE,
    prevalence = FALSE,
    prevalence_attrition = FALSE,
    survival = FALSE,
    summarise_log_file = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # cohort_code_use -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$cohort_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$cohort_code_use_cdm_name,
      input$cohort_code_use_variable_name,
      input$cohort_code_use_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$cohort_code_use, {
    if (updateButtons$cohort_code_use == TRUE) {
      output$update_message_cohort_code_use <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_cohort_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_cohort_code_use, {
    updateButtons$cohort_code_use <- FALSE
  })

  ## get cohort_code_use data
  getCohortCodeUseData <- shiny::eventReactive(input$update_cohort_code_use, {
    data[["cohort_code_use"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_code_use_cdm_name,
        .data$variable_name %in% input$cohort_code_use_variable_name,
        .data$estimate_name %in% input$cohort_code_use_estimate_name
      )
  })
  getCohortCodeUseTableReact <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        type = "reactable",
        header = "cdm_name"
      )
  })
  output$cohort_code_use_table_react <- reactable::renderReactable({
    getCohortCodeUseTableReact()
  })
  getCohortCodeUseTableGt <- shiny::reactive({
    getCohortCodeUseData() |>
      CodelistGenerator::tableCohortCodeUse(
        timing = TRUE,
        header = input$cohort_code_use_table_gt_header,
        groupColumn = input$cohort_code_use_table_gt_group_column,
        hide = input$cohort_code_use_table_gt_hide
      )
  })
  output$cohort_code_use_table_gt <- gt::render_gt({
    getCohortCodeUseTableGt()
  })
  output$cohort_code_use_table_gt_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_code_use.", input$cohort_code_use_table_gt_format),
    content = function(file) {
      gt::gtsave(getCohortCodeUseTableGt(), file)
    }
  )
  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_count <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_count_cdm_name,
      input$summarise_cohort_count_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })

  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      )
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      )
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_sex,
      input$summarise_characteristics_age_group,
      input$summarise_characteristics_region,
      input$summarise_characteristics_year_group,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$sex %in% input$summarise_characteristics_sex,
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$region %in% input$summarise_characteristics_region,
        .data$year_group %in% input$summarise_characteristics_year_group
      )
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_large_scale_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_large_scale_characteristics_cdm_name,
      input$summarise_large_scale_characteristics_cohort_name,
      input$summarise_large_scale_characteristics_age_group,
      input$summarise_large_scale_characteristics_region,
      input$summarise_large_scale_characteristics_year_group,
      input$summarise_large_scale_characteristics_sex,
      input$summarise_large_scale_characteristics_variable_level,
      input$summarise_large_scale_characteristics_table_name,
      input$summarise_large_scale_characteristics_type,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })

  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_large_scale_characteristics_age_group,
        .data$region %in% input$summarise_large_scale_characteristics_region,
        .data$year_group %in% input$summarise_large_scale_characteristics_year_group,
        .data$sex %in% input$summarise_large_scale_characteristics_sex
      ) |>
      omopgenerics::filterSettings(
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    }
    if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts,
        type = "gt"
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = paste0("top_concepts.", input$summarise_large_scale_characteristics_table_most_common_format),
    content = function(file) {
      gt::gtsave(getSummariseLargeScaleCharacteristicsTableMostCommon(), file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    if (input$summarise_large_scale_characteristics_plot_compared_missings) {
      mis <- 0
    } else {
      mis <- NULL
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = mis
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })
  # incidence -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$incidence <- TRUE
  }) |>
    shiny::bindEvent(
      input$incidence_cdm_name,
      input$incidence_region,
      input$incidence_incidence_start_date,
      input$incidence_analysis_interval,
      input$incidence_denominator_age_group,
      input$incidence_denominator_sex,
      input$incidence_variable_name,
      input$incidence_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$incidence, {
    if (updateButtons$incidence == TRUE) {
      output$update_message_incidence <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_incidence <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_incidence, {
    updateButtons$incidence <- FALSE
  })

  ## get incidence data
  getIncidenceData <- shiny::eventReactive(input$update_incidence, {
    data[["incidence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_cdm_name,
        .data$variable_name %in% input$incidence_variable_name,
        .data$estimate_name %in% input$incidence_estimate_name
      ) |>
      omopgenerics::filterStrata(.data$region %in% input$incidence_region) |>
      omopgenerics::filterAdditional(
        .data$incidence_start_date %in% input$incidence_incidence_start_date,
        .data$analysis_interval %in% input$incidence_analysis_interval
      ) |>
      omopgenerics::filterSettings(
        .data$denominator_age_group %in% input$incidence_denominator_age_group,
        .data$denominator_sex %in% input$incidence_denominator_sex
      )
  })
  getIncidenceTable <- shiny::reactive({
    res <- getIncidenceData()
    res |>
      IncidencePrevalence::tableIncidence(
        header = input$incidence_table_header,
        groupColumn = input$incidence_table_group_column,
        hide = input$incidence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$incidence_table <- gt::render_gt({
    getIncidenceTable()
  })
  output$incidence_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence.", input$incidence_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceTable(), file)
    }
  )
  getIncidencePlot <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidence(
        x = input$incidence_plot_x,
        facet = input$incidence_plot_facet,
        colour = input$incidence_plot_colour,
        ribbon = input$incidence_plot_ribbon,
        line = input$incidence_plot_line
      )
  })
  output$incidence_plot <- shiny::renderUI({
    x <- getIncidencePlot()
    renderInteractivePlot(x, input$incidence_plot_interactive)
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "plot_incidence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getIncidencePlot(),
        width = as.numeric(input$incidence_plot_width),
        height = as.numeric(input$incidence_plot_height),
        units = input$incidence_plot_units,
        dpi = as.numeric(input$incidence_plot_dpi)
      )
    }
  )
  getIncidencePlotPopulation <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidencePopulation(
        facet = input$incidence_plot_population_facet,
        colour = input$incidence_plot_population_colour
      )
  })
  output$incidence_plot_population <- shiny::renderUI({
    x <- getIncidencePlotPopulation()
    renderInteractivePlot(x, input$incidence_plot_population_interactive)
  })
  # incidence_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$incidence_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$incidence_attrition_cdm_name,
      input$incidence_attrition_denominator_age_group,
      input$incidence_attrition_denominator_sex,
      input$incidence_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$incidence_attrition, {
    if (updateButtons$incidence_attrition == TRUE) {
      output$update_message_incidence_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_incidence_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_incidence_attrition, {
    updateButtons$incidence_attrition <- FALSE
  })

  ## get incidence_attrition data
  getIncidenceAttritionData <- shiny::eventReactive(input$update_incidence_attrition, {
    data[["incidence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_attrition_cdm_name,
        .data$variable_name %in% input$incidence_attrition_variable_name
      ) |>
      omopgenerics::filterSettings(
        .data$denominator_age_group %in% input$incidence_attrition_denominator_age_group,
        .data$denominator_sex %in% input$incidence_attrition_denominator_sex
      )
  })
  getIncidenceAttritionTable <- shiny::reactive({
    res <- getIncidenceAttritionData()
    res |>
      IncidencePrevalence::tableIncidenceAttrition(
        header = input$incidence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$incidence_attrition_table_group_column,
        hide = input$incidence_attrition_table_hide
      )
  })
  output$incidence_attrition_table <- gt::render_gt({
    getIncidenceAttritionTable()
  })
  output$incidence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence_attrition.", input$incidence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceAttritionTable(), file)
    }
  )
  # prevalence -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$prevalence <- TRUE
  }) |>
    shiny::bindEvent(
      input$prevalence_cdm_name,
      input$prevalence_outcome_cohort_name,
      input$prevalence_region,
      input$prevalence_prevalence_start_date,
      input$prevalence_prevalence_end_date,
      input$prevalence_analysis_complete_database_intervals,
      input$prevalence_analysis_full_contribution,
      input$prevalence_analysis_type,
      input$prevalence_denominator_age_group,
      input$prevalence_denominator_sex,
      input$prevalence_variable_name,
      input$prevalence_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$prevalence, {
    if (updateButtons$prevalence == TRUE) {
      output$update_message_prevalence <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_prevalence <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_prevalence, {
    updateButtons$prevalence <- FALSE
  })

  ## get prevalence data
  getPrevalenceData <- shiny::eventReactive(input$update_prevalence, {
    data[["prevalence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_cdm_name,
        .data$variable_name %in% input$prevalence_variable_name,
        .data$estimate_name %in% input$prevalence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$prevalence_outcome_cohort_name) |>
      omopgenerics::filterStrata(.data$region %in% input$prevalence_region) |>
      omopgenerics::filterAdditional(
        .data$prevalence_start_date %in% input$prevalence_prevalence_start_date,
        .data$prevalence_end_date %in% input$prevalence_prevalence_end_date
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% input$prevalence_analysis_complete_database_intervals,
        .data$analysis_full_contribution %in% input$prevalence_analysis_full_contribution,
        .data$analysis_type %in% input$prevalence_analysis_type,
        .data$denominator_age_group %in% input$prevalence_denominator_age_group,
        .data$denominator_sex %in% input$prevalence_denominator_sex
      )
  })
  getPrevalenceTable <- shiny::reactive({
    res <- getPrevalenceData()
    res |>
      dplyr::mutate(estimate_value = dplyr::if_else(
        grepl("prevalence", estimate_name),
        as.character(10000 * as.numeric(estimate_value)),
        estimate_value
      )) |>
      IncidencePrevalence::tablePrevalence(
        header = input$prevalence_table_header,
        groupColumn = input$prevalence_table_group_column,
        hide = input$prevalence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      ) |>
      gt::tab_header(
        title = "Prevalence is expressed per 10,000 individuals"
      )
  })
  output$prevalence_table <- gt::render_gt({
    getPrevalenceTable()
  })
  output$prevalence_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence.", input$prevalence_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceTable(), file)
    }
  )
  getPrevalencePlot <- shiny::reactive({
    getPrevalenceData() |>
      IncidencePrevalence::plotPrevalence(
        x = input$prevalence_plot_x,
        facet = input$prevalence_plot_facet,
        colour = input$prevalence_plot_colour,
        ribbon = input$prevalence_plot_ribbon,
        line = input$prevalence_plot_line
      )
  })
  output$prevalence_plot <- shiny::renderUI({
    x <- getPrevalencePlot()
    renderInteractivePlot(x, input$prevalence_plot_interactive)
  })
  output$prevalence_plot_download <- shiny::downloadHandler(
    filename = "plot_prevalence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getPrevalencePlot(),
        width = as.numeric(input$prevalence_plot_width),
        height = as.numeric(input$prevalence_plot_height),
        units = input$prevalence_plot_units,
        dpi = as.numeric(input$prevalence_plot_dpi)
      )
    }
  )
  getPrevalencePlotPopulation <- shiny::reactive({
    getPrevalenceData() |>
      IncidencePrevalence::plotPrevalencePopulation(
        facet = input$prevalence_plot_population_facet,
        colour = input$prevalence_plot_population_colour
      )
  })
  output$prevalence_plot_population <- shiny::renderUI({
    x <- getPrevalencePlotPopulation()
    renderInteractivePlot(x, input$prevalence_plot_population_interactive)
  })
  # prevalence_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$prevalence_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$prevalence_attrition_cdm_name,
      input$prevalence_attrition_outcome_cohort_name,
      input$prevalence_attrition_analysis_complete_database_intervals,
      input$prevalence_attrition_analysis_full_contribution,
      input$prevalence_attrition_analysis_type,
      input$prevalence_attrition_denominator_age_group,
      input$prevalence_attrition_denominator_sex,
      input$prevalence_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$prevalence_attrition, {
    if (updateButtons$prevalence_attrition == TRUE) {
      output$update_message_prevalence_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_prevalence_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_prevalence_attrition, {
    updateButtons$prevalence_attrition <- FALSE
  })

  ## get prevalence_attrition data
  getPrevalenceAttritionData <- shiny::eventReactive(input$update_prevalence_attrition, {
    data[["prevalence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_attrition_cdm_name,
        .data$variable_name %in% input$prevalence_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$prevalence_attrition_outcome_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% input$prevalence_attrition_analysis_complete_database_intervals,
        .data$analysis_full_contribution %in% input$prevalence_attrition_analysis_full_contribution,
        .data$analysis_type %in% input$prevalence_attrition_analysis_type,
        .data$denominator_age_group %in% input$prevalence_attrition_denominator_age_group,
        .data$denominator_sex %in% input$prevalence_attrition_denominator_sex
      )
  })
  getPrevalenceAttritionTable <- shiny::reactive({
    res <- getPrevalenceAttritionData()
    res |>
      IncidencePrevalence::tablePrevalenceAttrition(
        header = input$prevalence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$prevalence_attrition_table_group_column,
        hide = input$prevalence_attrition_table_hide
      )
  })
  output$prevalence_attrition_table <- gt::render_gt({
    getPrevalenceAttritionTable()
  })
  output$prevalence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence_attrition.", input$prevalence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceAttritionTable(), file)
    }
  )
  # survival -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$survival <- TRUE
  }) |>
    shiny::bindEvent(
      input$survival_cdm_name,
      input$survival_target_cohort,
      input$survival_sex,
      input$survival_age_group,
      input$survival_region,
      input$survival_year_group,
      input$survival_reason,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$survival, {
    if (updateButtons$survival == TRUE) {
      output$update_message_survival <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_survival <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_survival, {
    updateButtons$survival <- FALSE
  })

  ## get survival data
  getSurvivalData <- shiny::eventReactive(input$update_survival, {
    data[["survival"]] |>
      dplyr::filter(.data$cdm_name %in% input$survival_cdm_name) |>
      omopgenerics::filterGroup(.data$target_cohort %in% input$survival_target_cohort) |>
      omopgenerics::filterStrata(
        .data$sex %in% input$survival_sex,
        .data$age_group %in% input$survival_age_group,
        .data$region %in% input$survival_region,
        .data$year_group %in% input$survival_year_group,
        .data$reason %in% input$survival_reason
      )
  })
  getSurvivalTableSurvival <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvival(
        timeScale = input$survival_table_survival_time_scale,
        type = "gt"
      )
  })
  output$survival_table_survival <- gt::render_gt({
    getSurvivalTableSurvival()
  })
  output$survival_table_survival_download <- shiny::downloadHandler(
    filename = paste0("table_survival_summary.", input$survival_table_survival_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableSurvival(), file)
    }
  )
  getSurvivalTableEvents <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvivalEvents(
        type = "gt"
      )
  })
  output$survival_table_events <- gt::render_gt({
    getSurvivalTableEvents()
  })
  output$survival_table_events_download <- shiny::downloadHandler(
    filename = paste0("table_survival_events.", input$survival_table_events_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableEvents(), file)
    }
  )
  getSurvivalTableAttrition <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::tableSurvivalAttrition(
        type = "gt"
      )
  })
  output$survival_table_attrition <- gt::render_gt({
    getSurvivalTableAttrition()
  })
  output$survival_table_attrition_download <- shiny::downloadHandler(
    filename = paste0("table_survival_attrition.", input$survival_table_attrition_format),
    content = function(file) {
      gt::gtsave(getSurvivalTableAttrition(), file)
    }
  )
  getSurvivalPlotSurvival <- shiny::reactive({
    getSurvivalData() |>
      CohortSurvival::plotSurvival(
        facet = input$survival_plot_survival_facet,
        colour = input$survival_plot_survival_colour,
        cumulativeFailure = input$survival_plot_survival_cumulative_failure,
        logLog = input$survival_plot_survival_log_log,
        timeScale = input$survival_plot_survival_time_scale
      )
  })
  output$survival_plot_survival <- shiny::renderUI({
    x <- getSurvivalPlotSurvival()
    renderInteractivePlot(x, input$survival_plot_survival_interactive)
  })
  output$survival_plot_survival_download <- shiny::downloadHandler(
    filename = "plot_survival.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSurvivalPlotSurvival(),
        width = as.numeric(input$survival_plot_survival_width),
        height = as.numeric(input$survival_plot_survival_height),
        units = input$survival_plot_survival_units,
        dpi = as.numeric(input$survival_plot_survival_dpi)
      )
    }
  )
  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    }
  )
}
