# Generated by OmopViewer 0.6.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CodelistGenerator",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort code use",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_cohort_code_use",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_cohort_code_use")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_cdm_name",
            label = "CDM name",
            choices = choices$cohort_code_use_cdm_name,
            selected = selected$cohort_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_variable_name",
            label = "Variable name",
            choices = choices$cohort_code_use_variable_name,
            selected = selected$cohort_code_use_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "cohort_code_use_estimate_name",
            label = "Estimate name",
            choices = choices$cohort_code_use_estimate_name,
            selected = selected$cohort_code_use_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Cohort code use (reactable)",
            bslib::card(
              full_screen = TRUE,
              reactable::reactableOutput("cohort_code_use_table_react") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table Cohort code use (gt)",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "cohort_code_use_table_gt_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "cohort_code_use_table_gt_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cohort_name", "codelist_name", "source_concept_name", "source_concept_id", "source_concept_value", "domain_id", "variable_name", "variable_level"),
                      input_id = "cohort_code_use_table_gt_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "estimate_name"),
                      input_id = "cohort_code_use_table_gt_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "cohort_code_use_table_gt_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("cohort_code_use_table_gt") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "CohortCharacteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_count",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_count")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_count_cdm_name,
            selected = selected$summarise_cohort_count_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_count_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_count_variable_name,
            selected = selected$summarise_cohort_count_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "estimate_name"),
                      input_id = "summarise_cohort_count_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "cdm_name",
                      input_id = "summarise_cohort_count_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "table_name"),
                      input_id = "summarise_cohort_count_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Counts",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_cohort_count_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_cohort_count_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "reason_id", "estimate_name", "age_range", "cdm_version", "cohort_definition_id", "min_prior_observation", "table_name", "vocabulary_version"),
                      input_id = "summarise_cohort_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_sex",
            label = "Sex",
            choices = choices$summarise_characteristics_sex,
            selected = selected$summarise_characteristics_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_age_group",
            label = "Age group",
            choices = choices$summarise_characteristics_age_group,
            selected = selected$summarise_characteristics_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_region",
            label = "Region",
            choices = choices$summarise_characteristics_region,
            selected = selected$summarise_characteristics_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_year_group",
            label = "Year group",
            choices = choices$summarise_characteristics_year_group,
            selected = selected$summarise_characteristics_year_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("sex", "age_group", "region", "year_group", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "sex", "age_group", "region", "year_group"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "sex", "age_group", "region", "year_group"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_large_scale_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_large_scale_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_large_scale_characteristics_cdm_name,
            selected = selected$summarise_large_scale_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_large_scale_characteristics_cohort_name,
            selected = selected$summarise_large_scale_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_age_group",
            label = "Age group",
            choices = choices$summarise_large_scale_characteristics_age_group,
            selected = selected$summarise_large_scale_characteristics_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_region",
            label = "Region",
            choices = choices$summarise_large_scale_characteristics_region,
            selected = selected$summarise_large_scale_characteristics_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_year_group",
            label = "Year group",
            choices = choices$summarise_large_scale_characteristics_year_group,
            selected = selected$summarise_large_scale_characteristics_year_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_sex",
            label = "Sex",
            choices = choices$summarise_large_scale_characteristics_sex,
            selected = selected$summarise_large_scale_characteristics_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_variable_level",
            label = "Variable level",
            choices = choices$summarise_large_scale_characteristics_variable_level,
            selected = selected$summarise_large_scale_characteristics_variable_level,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_table_name",
            label = "Table name",
            choices = choices$summarise_large_scale_characteristics_table_name,
            selected = selected$summarise_large_scale_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_large_scale_characteristics_type",
            label = "Type",
            choices = choices$summarise_large_scale_characteristics_type,
            selected = selected$summarise_large_scale_characteristics_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_lsc_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_compare_by",
                    label = "Compare by",
                    choices = c("no compare", "cdm_name", "cohort_name", "age_group", "region", "year_group", "sex", "type", "variable_level"),
                    selected = "no compare",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_hide",
                    label = "Hide",
                    choices = c("cdm_name", "cohort_name", "age_group", "region", "year_group", "sex", "type", "variable_level"),
                    selected = "type",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
                    label = "SMD reference",
                    choices = "no SMD",
                    selected = "no SMD",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                reactable::reactableOutput("summarise_large_scale_characteristics_table_lsc") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Most common codes",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_table_most_common_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_table_most_common_top_concepts",
                    label = "Top concepts",
                    choices = c(10L, 25L, 100L),
                    selected = 10L,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_table_most_common") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Compared",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shiny.fluent::Toggle.shinyInput(
                    label = "Missing data",
                    onText = "Interpolate 0",
                    offText = "Eliminate",
                    value = TRUE,
                    inputId = "summarise_large_scale_characteristics_plot_compared_missings"
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name", "age_group", "region", "year_group", "sex", "type", "variable_level"),
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_reference",
                    label = "Reference",
                    choices = NULL,
                    selected = NULL,
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_plot_compared_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "age_group", "region", "year_group", "sex", "type", "variable_level"),
                    selected = c("cdm_name", "cohort_name", "age_group", "region", "year_group", "sex"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                plotly::plotlyOutput("summarise_large_scale_characteristics_plot_compared") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "IncidencePrevalence",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Incidence",
      icon = shiny::icon("chart-line"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_incidence",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_incidence")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_cdm_name",
            label = "CDM name",
            choices = choices$incidence_cdm_name,
            selected = selected$incidence_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_region",
            label = "Region",
            choices = choices$incidence_region,
            selected = selected$incidence_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_incidence_start_date",
            label = "Incidence start date",
            choices = choices$incidence_incidence_start_date,
            selected = selected$incidence_incidence_start_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_analysis_interval",
            label = "Analysis interval",
            choices = choices$incidence_analysis_interval,
            selected = selected$incidence_analysis_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_denominator_age_group",
            label = "Denominator age group",
            choices = choices$incidence_denominator_age_group,
            selected = selected$incidence_denominator_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_denominator_sex",
            label = "Denominator sex",
            choices = choices$incidence_denominator_sex,
            selected = selected$incidence_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_variable_name",
            label = "Variable name",
            choices = choices$incidence_variable_name,
            selected = selected$incidence_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_estimate_name",
            label = "Estimate name",
            choices = choices$incidence_estimate_name,
            selected = selected$incidence_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Incidence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "incidence_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("region", "incidence_start_date", "incidence_end_date", "denominator_age_group", "denominator_sex"),
                      input_id = "incidence_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "estimate_name",
                      input_id = "incidence_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "incidence_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "incidence_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("incidence_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Incidence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "incidence_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "incidence_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "incidence_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "incidence_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_x",
                    label = "x axis",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "incidence_start_date",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_ribbon",
                    label = "Ribbon",
                    value = TRUE
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_line",
                    label = "Line",
                    value = TRUE
                  ),
                  position = "right"
                ),
                shiny::uiOutput("incidence_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot population",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "incidence_plot_population_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_population_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_plot_population_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("incidence_plot_population") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Incidence Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_incidence_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_incidence_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_attrition_cdm_name",
            label = "CDM name",
            choices = choices$incidence_attrition_cdm_name,
            selected = selected$incidence_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_attrition_denominator_age_group",
            label = "Denominator age group",
            choices = choices$incidence_attrition_denominator_age_group,
            selected = selected$incidence_attrition_denominator_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_attrition_denominator_sex",
            label = "Denominator sex",
            choices = choices$incidence_attrition_denominator_sex,
            selected = selected$incidence_attrition_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "incidence_attrition_variable_name",
            label = "Variable name",
            choices = choices$incidence_attrition_variable_name,
            selected = selected$incidence_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Incidence Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "incidence_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "incidence_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "incidence_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "incidence_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "estimate_name", "reason_id", "variable_level", "analysis_censor_cohort_name", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "incidence_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("incidence_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Prevalence",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_prevalence",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_prevalence")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_cdm_name",
            label = "CDM name",
            choices = choices$prevalence_cdm_name,
            selected = selected$prevalence_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_outcome_cohort_name",
            label = "Outcome cohort name",
            choices = choices$prevalence_outcome_cohort_name,
            selected = selected$prevalence_outcome_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_region",
            label = "Region",
            choices = choices$prevalence_region,
            selected = selected$prevalence_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_prevalence_start_date",
            label = "Prevalence start date",
            choices = choices$prevalence_prevalence_start_date,
            selected = selected$prevalence_prevalence_start_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_prevalence_end_date",
            label = "Prevalence end date",
            choices = choices$prevalence_prevalence_end_date,
            selected = selected$prevalence_prevalence_end_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_analysis_complete_database_intervals",
            label = "Analysis complete database intervals",
            choices = choices$prevalence_analysis_complete_database_intervals,
            selected = selected$prevalence_analysis_complete_database_intervals,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_analysis_full_contribution",
            label = "Analysis full contribution",
            choices = choices$prevalence_analysis_full_contribution,
            selected = selected$prevalence_analysis_full_contribution,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_analysis_type",
            label = "Analysis type",
            choices = choices$prevalence_analysis_type,
            selected = selected$prevalence_analysis_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_age_group",
            label = "Denominator age group",
            choices = choices$prevalence_denominator_age_group,
            selected = selected$prevalence_denominator_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_sex",
            label = "Denominator sex",
            choices = choices$prevalence_denominator_sex,
            selected = selected$prevalence_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_variable_name",
            label = "Variable name",
            choices = choices$prevalence_variable_name,
            selected = selected$prevalence_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_estimate_name",
            label = "Estimate name",
            choices = choices$prevalence_estimate_name,
            selected = selected$prevalence_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Prevalence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "prevalence_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("region", "prevalence_start_date", "prevalence_end_date", "denominator_age_group", "denominator_sex"),
                      input_id = "prevalence_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "estimate_name",
                      input_id = "prevalence_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "prevalence_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "prevalence_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("prevalence_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Prevalence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "prevalence_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "prevalence_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "prevalence_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "prevalence_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_x",
                    label = "x axis",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_level", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "prevalence_start_date",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_level", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_level", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_ribbon",
                    label = "Ribbon",
                    value = TRUE
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_line",
                    label = "Line",
                    value = TRUE
                  ),
                  position = "right"
                ),
                shiny::uiOutput("prevalence_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot population",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_population_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_population_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_level", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_population_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "region", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_level", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("prevalence_plot_population") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Prevalence Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_prevalence_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_prevalence_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_cdm_name",
            label = "CDM name",
            choices = choices$prevalence_attrition_cdm_name,
            selected = selected$prevalence_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_outcome_cohort_name",
            label = "Outcome cohort name",
            choices = choices$prevalence_attrition_outcome_cohort_name,
            selected = selected$prevalence_attrition_outcome_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_analysis_complete_database_intervals",
            label = "Analysis complete database intervals",
            choices = choices$prevalence_attrition_analysis_complete_database_intervals,
            selected = selected$prevalence_attrition_analysis_complete_database_intervals,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_analysis_full_contribution",
            label = "Analysis full contribution",
            choices = choices$prevalence_attrition_analysis_full_contribution,
            selected = selected$prevalence_attrition_analysis_full_contribution,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_analysis_type",
            label = "Analysis type",
            choices = choices$prevalence_attrition_analysis_type,
            selected = selected$prevalence_attrition_analysis_type,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_age_group",
            label = "Denominator age group",
            choices = choices$prevalence_attrition_denominator_age_group,
            selected = selected$prevalence_attrition_denominator_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_sex",
            label = "Denominator sex",
            choices = choices$prevalence_attrition_denominator_sex,
            selected = selected$prevalence_attrition_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_variable_name",
            label = "Variable name",
            choices = choices$prevalence_attrition_variable_name,
            selected = selected$prevalence_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Prevalence Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "prevalence_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "prevalence_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "prevalence_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "prevalence_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "estimate_name", "reason_id", "variable_level", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "prevalence_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("prevalence_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Survival Analyses",
    icon = shiny::icon("stairs"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_survival",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_survival")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_cdm_name",
          label = "CDM name",
          choices = choices$survival_cdm_name,
          selected = selected$survival_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_target_cohort",
          label = "Target cohort",
          choices = choices$survival_target_cohort,
          selected = selected$survival_target_cohort,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_sex",
          label = "Sex",
          choices = choices$survival_sex,
          selected = selected$survival_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_age_group",
          label = "Age group",
          choices = choices$survival_age_group,
          selected = selected$survival_age_group,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_region",
          label = "Region",
          choices = choices$survival_region,
          selected = selected$survival_region,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_year_group",
          label = "Year group",
          choices = choices$survival_year_group,
          selected = selected$survival_year_group,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "survival_reason",
          label = "Reason",
          choices = choices$survival_reason,
          selected = selected$survival_reason,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Summary",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_survival_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_survival_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "survival_table_survival_time_scale",
                  label = "Time Scale",
                  choices = c("days", "months", "years"),
                  selected = "days",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              gt::gt_output("survival_table_survival") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table Events",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_events_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_events_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("survival_table_events") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Table Attrition",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "survival_table_attrition_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "survival_table_attrition_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("survival_table_attrition") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Survival",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "survival_plot_survival_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "survival_plot_survival_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "survival_plot_survival_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "survival_plot_survival_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_cumulative_failure",
                  label = "Cumulative failure",
                  value = FALSE
                ),
                shinyWidgets::materialSwitch(
                  inputId = "survival_plot_survival_log_log",
                  label = "Log-Log plot",
                  value = FALSE
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_time_scale",
                  label = "Time Scale",
                  choices = c("days", "months", "years"),
                  selected = "days",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_facet",
                  label = "Facet",
                  choices = c("cdm_name", "target_cohort", "sex", "age_group", "region", "year_group", "reason", "time", "reason_id", "analysis_type", "censor_on_cohort_exit", "competing_outcome", "eventgap", "follow_up_days", "minimum_survival_days", "outcome", "outcome_date_variable", "outcome_washout"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "survival_plot_survival_colour",
                  label = "Colour",
                  choices = c("cdm_name", "target_cohort", "sex", "age_group", "region", "year_group", "reason", "time", "reason_id", "analysis_type", "censor_on_cohort_exit", "competing_outcome", "eventgap", "follow_up_days", "minimum_survival_days", "outcome", "outcome_date_variable", "outcome_washout"),
                  selected = "target_cohort",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("survival_plot_survival") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.6.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
